kind: ConfigMap 
apiVersion: v1 
metadata:
  name: configmap 
data:
  # Configuration values can be set as key-value properties
  WORDPRESS_DB_HOST: wordpress-mysql
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_PASSWORD: PassWord00
